// English copy. Items marked PROVISIONAL are placeholders.

export default {
  lang: 'en',
  htmlLang: 'en',
  hreflang: 'en',
  locale: 'en_GB',
  skip: 'Skip to content',
  nav: {
    menus: 'Menus', philosophy: 'Philosophy', events: 'Private dining', gift: 'Gift', contact: 'Contact',
    booking: 'Book', open: 'Menu', close: 'Close', primary: 'Main navigation', languages: 'Language',
  },
  theme: { label: 'Light', auto: 'Automatic', day: 'Day', night: 'Night', hint: 'The site follows the light in our dining room: bright by day, dark by night.' },
  footer: {
    visit: 'Visit', hours: 'Opening hours', contact: 'Contact', explore: 'Explore', closed: 'Closed',
    directions: 'Directions', legal: 'Legal notice', privacy: 'Privacy', cookies: 'Cookies',
    manage: 'Manage my booking', rights: 'All rights reserved',
  },
  live: {
    today: 'Today', open: 'Tables available', few: 'Last tables', full: 'Fully booked', closed: 'Closed today',
    past: 'Service closed', loading: 'Checking availability…', book: 'Book', localTime: 'Local time',
    next: 'Next available table',
  },
  seasons: ['Winter', 'Spring', 'Summer', 'Autumn'],

  home: {
    title: "Chef's tasting menus",
    meta: ['Chef-driven cuisine', 'Dénia · Alicante'],
    lede: 'Two tasting menus, twenty-four guests and whatever the land decides each week.',
    cta: 'Book a table',
    scroll: 'Discover',
    manifestoEyebrow: 'Philosophy',
    manifesto: 'We cook with what grows, is fished and raised within fifty kilometres. The menu changes <em>when the landscape changes</em>; the room is small on purpose, so every dish arrives on time and every conversation can be heard.',
    manifestoLink: 'How we cook',
    menusEyebrow: 'Menus',
    menusTitle: 'Two ways through the season',
    menusLink: 'See the full menus',
    chefEyebrow: 'Kitchen',
    quote: 'We are not trying to surprise you. We want you to recognise the taste of something that was always here.',
    chefRole: 'Chef',
    producersEyebrow: 'Origin',
    producersTitle: 'The people behind every dish',
    visitEyebrow: 'Visit',
    visitTitle: 'A table <em>awaits</em>',
    visitText: 'Our book opens two months in advance. For groups of more than six, write to us and we will plan it together.',
  },

  // PROVISIONAL
  producers: [
    ['Day-boat fish', 'Dénia fish market', '4 km'],
    ['Rice', 'Pego-Oliva wetlands', '22 km'],
    ['Vegetables & fruit', 'Huerta de la Vall', '4 km'],
    ['Olive oil', 'Almazara de la Sierra', '15 km'],
    ['Cheese', 'Mountain dairy', '31 km'],
    ['Wine', 'Marina Alta wineries', '18 km'],
  ],

  menus: {
    title: 'Menus',
    lead: 'Two tasting menus that change with the market. Both are served at lunch and dinner, for the whole table.',
    hint: 'Hover over each course to see the dish',
    notesTitle: 'Before you come',
    notes: [
      'We adapt our menus to allergies, intolerances and vegetarian diets if you let us know when booking.',
      'Approximate length: Origen, two and a half hours; Bagatge, three and a half hours.',
      'Prices per guest, VAT included. Filtered water and house bread included.',
      'Allergen information for every dish is available in the dining room (EU Regulation 1169/2011).',
      'The menu is served to the whole table. Dishes may vary with the day’s market.',
    ],
    illustration: 'Illustrations generated from the ingredients of each dish.',
  },

  philosophy: {
    title: 'Philosophy',
    lead: 'A small restaurant on Les Marines in Dénia, between the sea and the Montgó, cooking the landscape around it.',
    pillars: [
      ['Produce', 'We work with fishermen, growers and shepherds we know by name. If something does not arrive, the dish does not go out: the menu follows nature, not the other way round.'],
      ['Time', 'We ferment, cure and age in-house. Some preparations start weeks before you sit down; others are finished in front of you.'],
      ['Room', 'Twenty-four seats, a counter facing the kitchen and a team that tells you where everything comes from. No rush, no second sittings.'],
    ],
    chefTitle: 'The chef',
    chefBio: 'Joan Sastre is the chef at Bagatge. The cooking starts from the memory of the region and contemporary technique, and is rewritten every week with what comes in from the orchard and the fish market.', // PROVISIONAL: to be reviewed with the chef
    teamTitle: 'Team',
    team: [
      ['Kitchen', 'Joan Sastre', 'Chef'],
      ['Kitchen', 'Name Surname', 'Head chef'],
      ['Dining room', 'Name Surname', 'Restaurant manager'],
      ['Cellar', 'Name Surname', 'Sommelier'],
    ],
    roomTitle: 'The room',
    roomText: 'Twenty-four seats: an eight-seat counter facing the kitchen, three tables for four and two for two. One lunch and one dinner service.',
    producersTitle: 'Producers',
    kitchen: 'kitchen',
  },

  events: {
    title: 'Private dining',
    lead: 'The whole room for twenty-four guests, the chef’s counter for eight, or a menu designed around your celebration.',
    options: [
      ['The room', 'Up to 24 guests', 'Exclusive use of the restaurant, lunch or dinner, with a bespoke menu and pairing.'],
      ['Chef’s counter', '6 to 8 guests', 'Facing the kitchen, with the team serving and explaining every course.'],
      ['Bespoke', 'Companies & celebrations', 'Launches, anniversaries, proposals or team lunches. Let’s design it together.'],
    ],
    formTitle: 'Tell us your idea',
    formText: 'We reply within 48 hours with availability and a proposal.',
    types: ['Celebration', 'Company', 'Private dinner', 'Other'],
    budgets: ['Under €100 per guest', '€100–150 per guest', '€150–250 per guest', 'Over €250 per guest'],
    planLabel: 'Floor plan of the 24-seat dining room',
  },

  gift: {
    title: 'Give a table',
    lead: 'A gift card for any of our menus, with or without pairing. Valid for twelve months from issue.',
    steps: [
      ['Choose', 'Menu, pairing and number of guests.'],
      ['Confirm', 'We send you a secure payment link within a few hours.'],
      ['Give', 'You receive the digital or printed card with its personal code.'],
    ],
    formTitle: 'Your gift card',
    cardFor: 'For',
    cardValid: 'Valid 12 months',
    total: 'Amount',
    noPairing: 'No pairing',
    delivery: { email: 'Digital card by email', print: 'Printed card (collect at the restaurant)' },
  },

  contact: {
    title: 'Contact',
    lead: 'For reservations, the online form is the quickest way. For everything else, we are here.',
    address: 'Address',
    phone: 'Phone',
    email: 'Email',
    hours: 'Opening hours',
    access: 'Accessibility',
    accessText: 'Step-free dining room and accessible restroom.',
    parking: 'Parking',
    parkingText: 'Free public car park a two-minute walk away.',
    formTitle: 'Write to us',
  },

  forms: {
    name: 'Full name', email: 'Email', phone: 'Phone', company: 'Company (optional)', date: 'Preferred date (optional)',
    guests: 'Guests', eventType: 'Type of event', budget: 'Budget', message: 'Message', subject: 'Subject',
    recipient: 'Recipient’s name', recipientEmail: 'Recipient’s email (optional)', dedication: 'Personal message (optional)',
    delivery: 'Delivery', menu: 'Menu', pairing: 'Pairing', diners: 'Guests',
    buyer: 'Your details', select: 'Select…', optional: 'optional',
    consent: 'I have read and accept the <a href="{privacy}">privacy policy</a>.',
    marketing: 'I would like to receive occasional news from the house (menu changes, special dinners).',
    send: 'Send', sending: 'Sending…',
    sent: 'Received. We will get back to you shortly.',
    sentGift: 'Request received. We will email you the payment link and details.',
    error: 'We could not send it. Please check the details or try again later.',
    network: 'No connection to the server. Please try again.',
    required: 'Required field',
    captcha: 'Anti-spam check',
  },

  booking: {
    title: 'Reservations',
    lead: 'Choose a day and time. You will receive your confirmation by email straight away.',
    sentence: { table: 'Table for', at: 'at', menu: 'Menu', one: 'guest', other: 'guests' },
    steps: { party: 'How many of you?', date: 'Which day?', time: 'What time?', menu: 'Which menu?', details: 'Your details' },
    stepWord: 'Step',
    courses: 'courses',
    back: 'Back', next: 'Continue', change: 'Change',
    largeGroup: 'More than {n}? <a href="{events}">We host private events</a>.',
    prevMonth: 'Previous month', nextMonth: 'Next month',
    legend: { open: 'Available', few: 'Last tables', full: 'Full · waiting list', closed: 'Closed' },
    weekdays: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
    loading: 'Checking availability…',
    noSlots: 'No tables left for this day.',
    serviceFull: 'Full',
    fewLeft: 'Last tables',
    waitlistCta: 'Join the waiting list',
    waitlistTitle: 'Waiting list',
    waitlistText: 'If a table becomes available that day we will contact people in order. Joining does not guarantee a booking.',
    waitlistAny: 'Any service',
    waitlistDone: 'You are on the waiting list. If a table opens up, we will write to you.',
    menuUndecided: 'We’ll decide at the table',
    menuUndecidedText: 'You can choose your menu on the day.',
    pairingNone: 'No pairing',
    perPerson: 'per guest',
    dietary: 'Diets and restrictions',
    dietaryOptions: {
      vegetariano: 'Vegetarian', 'sin-gluten': 'Gluten-free', 'sin-lactosa': 'Lactose-free',
      marisco: 'No shellfish', 'frutos-secos': 'No nuts', embarazo: 'Pregnancy',
    },
    allergies: 'Allergies or intolerances',
    allergiesHint: 'Tell us everything we should know; we adapt every course.',
    occasion: 'Special occasion',
    occasionOptions: { '': 'None', cumpleanos: 'Birthday', aniversario: 'Anniversary', negocios: 'Business meal', celebracion: 'Celebration', primera: 'First visit' },
    notes: 'Anything else (optional)',
    policy: 'Free cancellation up to {h} hours before, using the link in your confirmation email.',
    submit: 'Confirm booking',
    submitRequest: 'Send request',
    submitting: 'Booking…',
    successTitle: 'Your table is booked',
    pendingTitle: 'Request received',
    pendingText: 'We will check availability and confirm by email within a few hours.',
    successText: 'We have emailed you the confirmation. Keep your reference.',
    successTextSms: 'We have sent your confirmation by email and text message. Keep your reference.',
    smsHint: 'We will text your confirmation to this number.',
    code: 'Reference',
    addCalendar: 'Add to calendar',
    google: 'Google Calendar',
    ics: 'Apple / Outlook (.ics)',
    manage: 'Manage or cancel',
    another: 'Make another booking',
    errors: {
      full: 'That time has just filled up. Please choose another.',
      duplicate: 'You already have a booking for that service. Check your email to manage it.',
      generic: 'We could not complete your booking. Please try again or call us.',
      unavailable: 'Online booking is not available right now. Please call us.',
    },
    calendarTitle: 'Table at {name}',
  },

  manage: {
    title: 'Your booking',
    lookupTitle: 'Manage a booking',
    lookupText: 'Enter the reference from your confirmation email and the email address you booked with.',
    code: 'Reference', email: 'Email', find: 'Find booking',
    notFound: 'We could not find a booking with those details.',
    status: {
      pending: 'Awaiting confirmation', confirmed: 'Confirmed', seated: 'Seated', completed: 'Completed',
      no_show: 'No-show', cancelled: 'Cancelled',
    },
    cancel: 'Cancel booking',
    cancelConfirm: 'Are you sure you want to cancel? The table will be released to someone else.',
    cancelLate: 'Less than {h} hours to go. You can still cancel, but we would appreciate a call if possible.',
    cancelled: 'Booking cancelled. We hope to see you another time.',
    cannotCancel: 'This booking can no longer be cancelled online. Please call us.',
    change: 'To change the date or party size, cancel and book again, or call us.',
    details: { date: 'Date', time: 'Time', party: 'Guests', menu: 'Menu', name: 'Name', allergies: 'Allergies' },
  },

  notFound: {
    title: 'This table does not exist',
    text: 'The page you are looking for has moved or was never here.',
    home: 'Back to home',
  },

  legal: { title: 'Legal notice', updated: 'Last updated' },
  privacy: { title: 'Privacy policy' },
  cookies: { title: 'Cookie policy' },
};
