// Textos de la web en castellano. Los marcados PROVISIONAL son de relleno
// hasta tener los datos reales (nombres del equipo, productores…).

export default {
  lang: 'es',
  htmlLang: 'es',
  hreflang: 'es',
  locale: 'es_ES',
  skip: 'Saltar al contenido',
  nav: {
    menus: 'Menús', philosophy: 'Filosofía', events: 'Eventos', gift: 'Regalo', contact: 'Contacto',
    booking: 'Reservar', open: 'Menú', close: 'Cerrar', primary: 'Navegación principal', languages: 'Idioma',
  },
  theme: { label: 'Luz', auto: 'Automática', day: 'Día', night: 'Noche', hint: 'La web sigue la luz de nuestra sala: clara de día, oscura de noche.' },
  footer: {
    visit: 'Visítanos', hours: 'Horario', contact: 'Contacto', explore: 'Explorar', closed: 'Cerrado',
    directions: 'Cómo llegar', legal: 'Aviso legal', privacy: 'Privacidad', cookies: 'Cookies',
    manage: 'Gestionar mi reserva', rights: 'Todos los derechos reservados',
  },
  live: {
    today: 'Hoy', open: 'Quedan mesas', few: 'Últimas mesas', full: 'Completo', closed: 'Hoy descansamos',
    past: 'Servicio cerrado', loading: 'Consultando disponibilidad…', book: 'Reservar', localTime: 'Hora local',
    next: 'Próxima mesa libre',
  },
  seasons: ['Invierno', 'Primavera', 'Verano', 'Otoño'],

  home: {
    title: 'Cocina de autor',
    meta: ['Cocina de autor', 'Pego · Alicante'],
    lede: 'Dos menús degustación, veinticuatro comensales y lo que la tierra decide cada semana.',
    cta: 'Reservar mesa',
    scroll: 'Descubrir',
    manifestoEyebrow: '01 — Filosofía',
    manifesto: 'Cocinamos con lo que crece, se pesca y se cría a menos de cincuenta kilómetros. El menú cambia <em>cuando cambia el paisaje</em>; la sala es pequeña a propósito, para que cada plato llegue a su tiempo y cada conversación se escuche.',
    manifestoLink: 'Nuestra manera de cocinar',
    figures: [
      ['24', 'comensales por servicio'],
      ['50', 'kilómetros de radio para el producto'],
      ['2', 'menús degustación'],
      ['1', 'temporada a la vez'],
    ],
    menusEyebrow: '02 — Menús',
    menusTitle: 'Dos maneras de recorrer la temporada',
    menusLink: 'Ver los menús completos',
    chefEyebrow: '03 — Cocina',
    quote: 'No buscamos sorprender. Buscamos que reconozcas el sabor de algo que siempre estuvo aquí.',
    chefRole: 'Chef y fundador',
    producersEyebrow: '04 — Origen',
    producersTitle: 'Las personas detrás de cada plato',
    visitEyebrow: '05 — Visita',
    visitTitle: 'Una mesa <em>te espera</em>',
    visitText: 'Abrimos el libro de reservas con dos meses de antelación. Para grupos de más de seis personas, escríbenos y lo preparamos juntos.',
  },

  // PROVISIONAL — productores de ejemplo
  producers: [
    ['Pescado de lonja', 'Lonja de Dénia', '22 km'],
    ['Arroz', 'Marjal de Pego-Oliva', '3 km'],
    ['Verdura y fruta', 'Huerta de la Vall', '4 km'],
    ['Aceite de oliva', 'Almazara de la Sierra', '15 km'],
    ['Quesos', 'Quesería de montaña', '31 km'],
    ['Vino', 'Bodegas de la Marina Alta', '18 km'],
  ],

  menus: {
    title: 'Menús',
    lead: 'Dos menús degustación que cambian con el mercado. Ambos se sirven a mediodía y por la noche, para toda la mesa.',
    hint: 'Pasa por cada tiempo para ver el plato',
    notesTitle: 'Antes de venir',
    notes: [
      'Adaptamos los menús a alergias, intolerancias y dietas vegetarianas si nos avisas al reservar.',
      'Duración aproximada: Origen, dos horas y media; Bagatge, tres horas y media.',
      'Precios por persona con IVA incluido. Agua filtrada y pan de la casa incluidos.',
      'La información de alérgenos de cada plato está disponible en sala (Reglamento UE 1169/2011).',
      'El menú se sirve a toda la mesa. Los platos pueden variar según el mercado del día.',
    ],
    illustration: 'Ilustraciones generadas a partir de los ingredientes de cada plato.',
  },

  philosophy: {
    title: 'Filosofía',
    lead: 'Un restaurante pequeño, en un pueblo pequeño, que cocina el paisaje que tiene alrededor.',
    pillars: [
      ['Producto', 'Trabajamos con pescadores, hortelanos y pastores a los que conocemos por su nombre. Si algo no llega, el plato no sale: el menú se ajusta a la naturaleza, no al revés.'],
      ['Tiempo', 'Fermentamos, curamos y maduramos en casa. Algunas elaboraciones empiezan semanas antes de que te sientes; otras se terminan delante de ti.'],
      ['Sala', 'Veinticuatro plazas, una barra frente a la cocina y un equipo que te explica de dónde viene cada cosa. Sin prisas, sin segundos turnos.'],
    ],
    chefTitle: 'El chef',
    chefBio: 'Formado en cocinas de España y Europa, volvió a la comarca para abrir un restaurante a la medida de su paisaje. Su cocina parte de la memoria familiar y la técnica contemporánea, y se escribe cada semana con lo que llega de la huerta y la lonja.', // PROVISIONAL
    teamTitle: 'Equipo',
    // PROVISIONAL
    team: [
      ['Cocina', 'Nombre del Chef', 'Chef'],
      ['Cocina', 'Nombre Apellido', 'Jefa de cocina'],
      ['Sala', 'Nombre Apellido', 'Jefe de sala'],
      ['Bodega', 'Nombre Apellido', 'Sumiller'],
    ],
    roomTitle: 'La sala',
    roomText: 'Veinticuatro plazas: una barra de ocho frente a la cocina, tres mesas de cuatro y dos de dos. Un solo servicio de mediodía y uno de noche.',
    producersTitle: 'Productores',
    kitchen: 'cocina',
  },

  events: {
    title: 'Eventos privados',
    lead: 'La sala completa para veinticuatro invitados, la barra del chef para ocho o un menú pensado para vuestra celebración.',
    options: [
      ['La sala', 'Hasta 24 invitados', 'El restaurante en exclusiva, a mediodía o por la noche, con menú y maridaje a medida.'],
      ['Barra del chef', 'De 6 a 8 invitados', 'Frente a la cocina, con el equipo sirviendo y explicando cada tiempo.'],
      ['A medida', 'Empresas y celebraciones', 'Presentaciones, aniversarios, pedidas o comidas de equipo. Hablamos y lo diseñamos contigo.'],
    ],
    formTitle: 'Cuéntanos tu idea',
    formText: 'Te respondemos en menos de 48 horas con disponibilidad y una propuesta.',
    types: ['Celebración', 'Empresa', 'Cena privada', 'Otro'],
    budgets: ['Menos de 100 € por persona', '100–150 € por persona', '150–250 € por persona', 'Más de 250 € por persona'],
    planLabel: 'Planta de la sala con 24 plazas',
  },

  gift: {
    title: 'Regala una mesa',
    lead: 'Una tarjeta regalo para cualquiera de nuestros menús, con o sin maridaje. Válida durante doce meses desde su emisión.',
    steps: [
      ['Elige', 'Menú, maridaje y número de comensales.'],
      ['Confirma', 'Te enviamos el enlace de pago seguro en unas horas.'],
      ['Regala', 'Recibes la tarjeta digital o impresa, con su código personal.'],
    ],
    formTitle: 'Tu tarjeta regalo',
    cardFor: 'Para',
    cardValid: 'Válida 12 meses',
    total: 'Importe',
    noPairing: 'Sin maridaje',
    delivery: { email: 'Tarjeta digital por email', print: 'Tarjeta impresa (recogida en el restaurante)' },
  },

  contact: {
    title: 'Contacto',
    lead: 'Para reservas, lo más rápido es el formulario online. Para todo lo demás, aquí estamos.',
    address: 'Dirección',
    phone: 'Teléfono',
    email: 'Email',
    hours: 'Horario',
    access: 'Accesibilidad',
    accessText: 'Sala accesible sin escalones y aseo adaptado.', // PROVISIONAL
    parking: 'Aparcamiento',
    parkingText: 'Aparcamiento público gratuito a dos minutos a pie.', // PROVISIONAL
    formTitle: 'Escríbenos',
  },

  forms: {
    name: 'Nombre y apellidos', email: 'Email', phone: 'Teléfono', company: 'Empresa (opcional)', date: 'Fecha deseada (opcional)',
    guests: 'Invitados', eventType: 'Tipo de evento', budget: 'Presupuesto', message: 'Mensaje', subject: 'Asunto',
    recipient: 'Nombre de quien la recibe', recipientEmail: 'Email de quien la recibe (opcional)', dedication: 'Dedicatoria (opcional)',
    delivery: 'Entrega', menu: 'Menú', pairing: 'Maridaje', diners: 'Comensales',
    buyer: 'Tus datos', select: 'Selecciona…', optional: 'opcional',
    consent: 'He leído y acepto la <a href="{privacy}">política de privacidad</a>.',
    marketing: 'Quiero recibir, muy de vez en cuando, noticias de la casa (cambios de menú, cenas especiales).',
    send: 'Enviar', sending: 'Enviando…',
    sent: 'Recibido. Te contestaremos en breve.',
    sentGift: 'Solicitud recibida. Te enviaremos el enlace de pago y los detalles por email.',
    error: 'No se ha podido enviar. Revisa los datos o inténtalo más tarde.',
    network: 'Sin conexión con el servidor. Inténtalo de nuevo.',
    required: 'Campo obligatorio',
    captcha: 'Verificación anti-spam',
  },

  booking: {
    title: 'Reservas',
    lead: 'Elige día y hora. Recibirás la confirmación al momento por email.',
    sentence: { table: 'Mesa para', at: 'a las', menu: 'Menú', one: 'persona', other: 'personas' },
    steps: { party: '¿Cuántos sois?', date: '¿Qué día?', time: '¿A qué hora?', menu: '¿Qué menú?', details: 'Tus datos' },
    stepWord: 'Paso',
    courses: 'tiempos',
    back: 'Atrás', next: 'Continuar', change: 'Cambiar',
    largeGroup: '¿Más de {n}? <a href="{events}">Organizamos eventos privados</a>.',
    prevMonth: 'Mes anterior', nextMonth: 'Mes siguiente',
    legend: { open: 'Disponible', few: 'Últimas mesas', full: 'Completo · lista de espera', closed: 'Cerrado' },
    weekdays: ['L', 'M', 'X', 'J', 'V', 'S', 'D'],
    loading: 'Consultando disponibilidad…',
    noSlots: 'No quedan mesas para este día.',
    serviceFull: 'Completo',
    fewLeft: 'Últimas mesas',
    waitlistCta: 'Apuntarme a la lista de espera',
    waitlistTitle: 'Lista de espera',
    waitlistText: 'Si se libera una mesa para ese día te avisamos por orden de llegada. Apuntarte no garantiza la reserva.',
    waitlistAny: 'Cualquier servicio',
    waitlistDone: 'Estás en la lista de espera. Si se libera una mesa, te escribiremos.',
    menuUndecided: 'Lo decidimos en la mesa',
    menuUndecidedText: 'Podéis elegir el menú el mismo día.',
    pairingNone: 'Sin maridaje',
    perPerson: 'por persona',
    dietary: 'Dietas y restricciones',
    dietaryOptions: {
      vegetariano: 'Vegetariana', 'sin-gluten': 'Sin gluten', 'sin-lactosa': 'Sin lactosa',
      marisco: 'Sin marisco', 'frutos-secos': 'Sin frutos secos', embarazo: 'Embarazo',
    },
    allergies: 'Alergias o intolerancias',
    allergiesHint: 'Cuéntanos todo lo que debamos saber; adaptamos cada tiempo.',
    occasion: 'Ocasión especial',
    occasionOptions: { '': 'Ninguna', cumpleanos: 'Cumpleaños', aniversario: 'Aniversario', negocios: 'Comida de negocios', celebracion: 'Celebración', primera: 'Primera visita' },
    notes: 'Algo más (opcional)',
    policy: 'Puedes cancelar sin coste hasta {h} horas antes desde el enlace del email de confirmación.',
    submit: 'Confirmar reserva',
    submitRequest: 'Enviar solicitud',
    submitting: 'Reservando…',
    successTitle: 'Tu mesa está reservada',
    pendingTitle: 'Solicitud recibida',
    pendingText: 'Revisaremos la disponibilidad y te confirmaremos por email en las próximas horas.',
    successText: 'Te hemos enviado la confirmación por email. Guarda tu localizador.',
    successTextSms: 'Te hemos enviado la confirmación por email y SMS. Guarda tu localizador.',
    smsHint: 'Te enviaremos la confirmación por SMS a este número.',
    code: 'Localizador',
    addCalendar: 'Añadir al calendario',
    google: 'Google Calendar',
    ics: 'Apple / Outlook (.ics)',
    manage: 'Gestionar o cancelar',
    another: 'Hacer otra reserva',
    errors: {
      full: 'Esa hora acaba de completarse. Elige otra, por favor.',
      duplicate: 'Ya tienes una reserva para ese servicio. Revisa tu email para gestionarla.',
      generic: 'No hemos podido completar la reserva. Inténtalo de nuevo o llámanos.',
      unavailable: 'Las reservas online no están disponibles ahora mismo. Llámanos y te atendemos.',
    },
    calendarTitle: 'Mesa en {name}',
  },

  manage: {
    title: 'Tu reserva',
    lookupTitle: 'Gestionar una reserva',
    lookupText: 'Introduce el localizador que aparece en tu email de confirmación y el email con el que reservaste.',
    code: 'Localizador', email: 'Email', find: 'Buscar reserva',
    notFound: 'No encontramos ninguna reserva con esos datos.',
    status: {
      pending: 'Pendiente de confirmar', confirmed: 'Confirmada', seated: 'En sala', completed: 'Completada',
      no_show: 'No presentada', cancelled: 'Cancelada',
    },
    cancel: 'Cancelar reserva',
    cancelConfirm: '¿Seguro que quieres cancelar? La mesa quedará libre para otra persona.',
    cancelLate: 'Faltan menos de {h} horas. Puedes cancelar igualmente, pero te agradeceremos que nos llames si es posible.',
    cancelled: 'Reserva cancelada. Esperamos verte en otra ocasión.',
    cannotCancel: 'Esta reserva ya no se puede cancelar online. Llámanos, por favor.',
    change: 'Para cambiar la fecha o el número de comensales, cancela y vuelve a reservar o llámanos.',
    details: { date: 'Fecha', time: 'Hora', party: 'Comensales', menu: 'Menú', name: 'Nombre', allergies: 'Alergias' },
  },

  notFound: {
    title: 'Esta mesa no existe',
    text: 'La página que buscas se ha movido o nunca estuvo aquí.',
    home: 'Volver al inicio',
  },

  legal: {
    title: 'Aviso legal',
    updated: 'Última actualización',
  },
  privacy: { title: 'Política de privacidad' },
  cookies: { title: 'Política de cookies' },
};
