// Textos de la web en valencià (idioma predeterminat). Els marcats PROVISIONAL
// són de farciment fins a tindre les dades reals (equip, productors…).

export default {
  lang: 'va',
  htmlLang: 'ca-valencia',
  hreflang: 'ca',
  locale: 'ca_ES',
  skip: 'Saltar al contingut',
  nav: {
    menus: 'Menús', philosophy: 'Filosofia', events: 'Esdeveniments', gift: 'Regal', contact: 'Contacte',
    booking: 'Reservar', open: 'Menú', close: 'Tancar', primary: 'Navegació principal', languages: 'Idioma',
  },
  theme: { label: 'Llum', auto: 'Automàtica', day: 'Dia', night: 'Nit', hint: 'La web seguix la llum de la nostra sala: clara de dia, fosca de nit.' },
  footer: {
    visit: 'Visita’ns', hours: 'Horari', contact: 'Contacte', explore: 'Explora', closed: 'Tancat',
    directions: 'Com arribar', legal: 'Avís legal', privacy: 'Privacitat', cookies: 'Galetes',
    manage: 'Gestionar la meua reserva', rights: 'Tots els drets reservats',
  },
  live: {
    today: 'Hui', open: 'Queden taules', few: 'Últimes taules', full: 'Complet', closed: 'Hui descansem',
    past: 'Servici tancat', loading: 'Consultant la disponibilitat…', book: 'Reservar', localTime: 'Hora local',
    next: 'Pròxima taula lliure',
  },
  seasons: ['Hivern', 'Primavera', 'Estiu', 'Tardor'],

  home: {
    title: 'Cuina d’autor',
    meta: ['Cuina d’autor', 'Pego · Alacant'],
    lede: 'Dos menús degustació, vint-i-quatre comensals i allò que la terra decidix cada setmana.',
    cta: 'Reservar taula',
    scroll: 'Descobrir',
    manifestoEyebrow: 'Filosofia',
    manifesto: 'Cuinem amb allò que creix, es pesca i es cria a menys de cinquanta quilòmetres. El menú canvia <em>quan canvia el paisatge</em>; la sala és xicoteta a propòsit, perquè cada plat arribe a temps i cada conversa s’escolte.',
    manifestoLink: 'La nostra manera de cuinar',
    menusEyebrow: 'Menús',
    menusTitle: 'Dues maneres de recórrer la temporada',
    menusLink: 'Vore els menús complets',
    chefEyebrow: 'Cuina',
    quote: 'No busquem sorprendre. Volem que reconegues el sabor d’alguna cosa que sempre ha estat ací.',
    chefRole: 'Xef',
    producersEyebrow: 'Origen',
    producersTitle: 'Les persones darrere de cada plat',
    visitEyebrow: 'Visita',
    visitTitle: 'Una taula <em>t’espera</em>',
    visitText: 'Obrim el llibre de reserves amb dos mesos d’antelació. Per a grups de més de sis persones, escriu-nos i ho preparem junts.',
  },

  // PROVISIONAL — productors d’exemple
  producers: [
    ['Peix de llotja', 'Llotja de Dénia', '22 km'],
    ['Arròs', 'Marjal de Pego-Oliva', '3 km'],
    ['Verdura i fruita', 'Horta de la Vall', '4 km'],
    ['Oli d’oliva', 'Almàssera de la Serra', '15 km'],
    ['Formatges', 'Formatgeria de muntanya', '31 km'],
    ['Vi', 'Cellers de la Marina Alta', '18 km'],
  ],

  menus: {
    title: 'Menús',
    lead: 'Dos menús degustació que canvien amb el mercat. Tots dos se servixen a migdia i a la nit, per a tota la taula.',
    hint: 'Passa per damunt de cada pas per a vore el plat',
    notesTitle: 'Abans de vindre',
    notes: [
      'Adaptem els menús a al·lèrgies, intoleràncies i dietes vegetarianes si ens ho dius en reservar.',
      'Duració aproximada: Origen, dues hores i mitja; Bagatge, tres hores i mitja.',
      'Preus per persona amb IVA inclòs. Aigua filtrada i pa de la casa inclosos.',
      'La informació d’al·lèrgens de cada plat està disponible a la sala (Reglament UE 1169/2011).',
      'El menú se servix a tota la taula. Els plats poden variar segons el mercat del dia.',
    ],
    illustration: 'Il·lustracions generades a partir dels ingredients de cada plat.',
  },

  philosophy: {
    title: 'Filosofia',
    lead: 'Un restaurant xicotet, en un poble xicotet, que cuina el paisatge que té al voltant.',
    pillars: [
      ['Producte', 'Treballem amb pescadors, hortolans i pastors que coneixem pel seu nom. Si alguna cosa no arriba, el plat no ix: el menú s’adapta a la natura, i no al revés.'],
      ['Temps', 'Fermentem, curem i madurem a casa. Algunes elaboracions comencen setmanes abans que t’assegues; altres s’acaben davant teu.'],
      ['Sala', 'Vint-i-quatre places, una barra davant de la cuina i un equip que t’explica d’on ve cada cosa. Sense presses i sense segons torns.'],
    ],
    chefTitle: 'El xef',
    chefBio: 'Joan Sastre és el xef de Bagatge. La seua cuina parteix de la memòria de la comarca i de la tècnica contemporània, i s’escriu cada setmana amb allò que arriba de l’horta i de la llotja.', // PROVISIONAL: text a revisar amb el xef
    teamTitle: 'Equip',
    // PROVISIONAL
    team: [
      ['Cuina', 'Joan Sastre', 'Xef'],
      ['Cuina', 'Nom Cognom', 'Cap de cuina'],
      ['Sala', 'Nom Cognom', 'Cap de sala'],
      ['Celler', 'Nom Cognom', 'Sommelier'],
    ],
    roomTitle: 'La sala',
    roomText: 'Vint-i-quatre places: una barra de huit davant de la cuina, tres taules de quatre i dues de dos. Un sol servici de migdia i un de nit.',
    producersTitle: 'Productors',
    kitchen: 'cuina',
  },

  events: {
    title: 'Esdeveniments privats',
    lead: 'La sala completa per a vint-i-quatre convidats, la barra del xef per a huit o un menú pensat per a la vostra celebració.',
    options: [
      ['La sala', 'Fins a 24 convidats', 'El restaurant en exclusiva, a migdia o a la nit, amb menú i maridatge a mida.'],
      ['Barra del xef', 'De 6 a 8 convidats', 'Davant de la cuina, amb l’equip servint i explicant cada pas.'],
      ['A mida', 'Empreses i celebracions', 'Presentacions, aniversaris, peticions de mà o dinars d’equip. En parlem i ho dissenyem amb tu.'],
    ],
    formTitle: 'Conta’ns la teua idea',
    formText: 'Et responem en menys de 48 hores amb disponibilitat i una proposta.',
    types: ['Celebració', 'Empresa', 'Sopar privat', 'Altres'],
    budgets: ['Menys de 100 € per persona', '100–150 € per persona', '150–250 € per persona', 'Més de 250 € per persona'],
    planLabel: 'Planta de la sala amb 24 places',
  },

  gift: {
    title: 'Regala una taula',
    lead: 'Una targeta regal per a qualsevol dels nostres menús, amb maridatge o sense. Vàlida durant dotze mesos des de l’emissió.',
    steps: [
      ['Tria', 'Menú, maridatge i nombre de comensals.'],
      ['Confirma', 'T’enviem l’enllaç de pagament segur en unes hores.'],
      ['Regala', 'Reps la targeta digital o impresa, amb el seu codi personal.'],
    ],
    formTitle: 'La teua targeta regal',
    cardFor: 'Per a',
    cardValid: 'Vàlida 12 mesos',
    total: 'Import',
    noPairing: 'Sense maridatge',
    delivery: { email: 'Targeta digital per correu electrònic', print: 'Targeta impresa (arreplegada al restaurant)' },
  },

  contact: {
    title: 'Contacte',
    lead: 'Per a reservar, el més ràpid és el formulari en línia. Per a tota la resta, ací estem.',
    address: 'Adreça',
    phone: 'Telèfon',
    email: 'Correu electrònic',
    hours: 'Horari',
    access: 'Accessibilitat',
    accessText: 'Sala accessible sense escalons i lavabo adaptat.', // PROVISIONAL
    parking: 'Aparcament',
    parkingText: 'Aparcament públic gratuït a dos minuts a peu.', // PROVISIONAL
    formTitle: 'Escriu-nos',
  },

  forms: {
    name: 'Nom i cognoms', email: 'Correu electrònic', phone: 'Telèfon', company: 'Empresa (opcional)', date: 'Data desitjada (opcional)',
    guests: 'Convidats', eventType: 'Tipus d’esdeveniment', budget: 'Pressupost', message: 'Missatge', subject: 'Assumpte',
    recipient: 'Nom de qui la rep', recipientEmail: 'Correu de qui la rep (opcional)', dedication: 'Dedicatòria (opcional)',
    delivery: 'Lliurament', menu: 'Menú', pairing: 'Maridatge', diners: 'Comensals',
    buyer: 'Les teues dades', select: 'Selecciona…', optional: 'opcional',
    consent: 'He llegit i accepte la <a href="{privacy}">política de privacitat</a>.',
    marketing: 'Vull rebre, de tant en tant, notícies de la casa (canvis de menú, sopars especials).',
    send: 'Enviar', sending: 'Enviant…',
    sent: 'Rebut. Et contestarem prompte.',
    sentGift: 'Sol·licitud rebuda. T’enviarem l’enllaç de pagament i els detalls per correu electrònic.',
    error: 'No s’ha pogut enviar. Revisa les dades o torna-ho a provar més tard.',
    network: 'Sense connexió amb el servidor. Torna-ho a provar.',
    required: 'Camp obligatori',
    captcha: 'Verificació antispam',
  },

  booking: {
    title: 'Reserves',
    lead: 'Tria dia i hora. Rebràs la confirmació a l’instant.',
    sentence: { table: 'Taula per a', at: 'a les', menu: 'Menú', one: 'persona', other: 'persones' },
    steps: { party: 'Quants sou?', date: 'Quin dia?', time: 'A quina hora?', menu: 'Quin menú?', details: 'Les teues dades' },
    stepWord: 'Pas',
    courses: 'passos',
    back: 'Arrere', next: 'Continuar', change: 'Canviar',
    largeGroup: 'Més de {n}? <a href="{events}">Organitzem esdeveniments privats</a>.',
    prevMonth: 'Mes anterior', nextMonth: 'Mes següent',
    legend: { open: 'Disponible', few: 'Últimes taules', full: 'Complet · llista d’espera', closed: 'Tancat' },
    weekdays: ['Dl', 'Dt', 'Dc', 'Dj', 'Dv', 'Ds', 'Dg'],
    loading: 'Consultant la disponibilitat…',
    noSlots: 'No queden taules per a este dia.',
    serviceFull: 'Complet',
    fewLeft: 'Últimes taules',
    waitlistCta: 'Apuntar-me a la llista d’espera',
    waitlistTitle: 'Llista d’espera',
    waitlistText: 'Si s’allibera una taula per a eixe dia, t’avisem per orde d’arribada. Apuntar-te no garantix la reserva.',
    waitlistAny: 'Qualsevol servici',
    waitlistDone: 'Estàs en la llista d’espera. Si s’allibera una taula, t’escriurem.',
    menuUndecided: 'Ho decidim a taula',
    menuUndecidedText: 'Podeu triar el menú el mateix dia.',
    pairingNone: 'Sense maridatge',
    perPerson: 'per persona',
    dietary: 'Dietes i restriccions',
    dietaryOptions: {
      vegetariano: 'Vegetariana', 'sin-gluten': 'Sense gluten', 'sin-lactosa': 'Sense lactosa',
      marisco: 'Sense marisc', 'frutos-secos': 'Sense fruita seca', embarazo: 'Embaràs',
    },
    allergies: 'Al·lèrgies o intoleràncies',
    allergiesHint: 'Conta’ns tot el que hàgem de saber; adaptem cada pas.',
    occasion: 'Ocasió especial',
    occasionOptions: { '': 'Cap', cumpleanos: 'Aniversari', aniversario: 'Aniversari de parella', negocios: 'Dinar de negocis', celebracion: 'Celebració', primera: 'Primera visita' },
    notes: 'Alguna cosa més (opcional)',
    policy: 'Pots cancel·lar sense cost fins a {h} hores abans des de l’enllaç de confirmació.',
    submit: 'Confirmar la reserva',
    submitRequest: 'Enviar la sol·licitud',
    submitting: 'Reservant…',
    successTitle: 'La teua taula està reservada',
    pendingTitle: 'Sol·licitud rebuda',
    pendingText: 'Revisarem la disponibilitat i et confirmarem la reserva en les pròximes hores.',
    successText: 'T’hem enviat la confirmació per correu electrònic. Guarda el localitzador.',
    successTextSms: 'T’hem enviat la confirmació per correu electrònic i SMS. Guarda el localitzador.',
    smsHint: 'T’enviarem la confirmació per SMS a este número.',
    code: 'Localitzador',
    addCalendar: 'Afegir al calendari',
    google: 'Google Calendar',
    ics: 'Apple / Outlook (.ics)',
    manage: 'Gestionar o cancel·lar',
    another: 'Fer una altra reserva',
    errors: {
      full: 'Eixa hora s’acaba de completar. Tria’n una altra, per favor.',
      duplicate: 'Ja tens una reserva per a eixe servici. Revisa el correu per a gestionar-la.',
      generic: 'No hem pogut completar la reserva. Torna-ho a provar o telefona’ns.',
      unavailable: 'Les reserves en línia no estan disponibles ara mateix. Telefona’ns i t’atendrem.',
    },
    calendarTitle: 'Taula a {name}',
  },

  manage: {
    title: 'La teua reserva',
    lookupTitle: 'Gestionar una reserva',
    lookupText: 'Introduïx el localitzador que apareix en el correu de confirmació i el correu electrònic amb què vas reservar.',
    code: 'Localitzador', email: 'Correu electrònic', find: 'Buscar la reserva',
    notFound: 'No trobem cap reserva amb estes dades.',
    status: {
      pending: 'Pendent de confirmar', confirmed: 'Confirmada', seated: 'A la sala', completed: 'Completada',
      no_show: 'No presentada', cancelled: 'Cancel·lada',
    },
    cancel: 'Cancel·lar la reserva',
    cancelConfirm: 'Segur que vols cancel·lar? La taula quedarà lliure per a una altra persona.',
    cancelLate: 'Falten menys de {h} hores. Pots cancel·lar igualment, però t’agrairem que ens telefones si és possible.',
    cancelled: 'Reserva cancel·lada. Esperem vore’t una altra vegada.',
    cannotCancel: 'Esta reserva ja no es pot cancel·lar en línia. Telefona’ns, per favor.',
    change: 'Per a canviar la data o el nombre de comensals, cancel·la i torna a reservar o telefona’ns.',
    details: { date: 'Data', time: 'Hora', party: 'Comensals', menu: 'Menú', name: 'Nom', allergies: 'Al·lèrgies' },
  },

  notFound: {
    title: 'Esta taula no existix',
    text: 'La pàgina que busques s’ha mogut o mai no ha estat ací.',
    home: 'Tornar a l’inici',
  },

  legal: { title: 'Avís legal', updated: 'Última actualització' },
  privacy: { title: 'Política de privacitat' },
  cookies: { title: 'Política de galetes' },
};
